### ISSUE TITLE
Can I use kit's IR sensor?

### ISSUE THREAD

**Issue by haizaar** [haizaar/doll-house-lights#1]
I thought if I buy a [kit](https://www.aliexpress.com/item/32817764805.html) to use IR remote, may be I can use the sensor as well? Cut is off and attach to arduino?

If it's not something straight-forward, let's skip it and I'll just buy a sensor as you mentioned.

**Comment by jim-sokoloff** [comment]
In principle, yes. In practice, the good IR sensors are 10 for $5 and you know the exact part number and pinout, so...

If you need to economize slightly, get the 10 for $2 versions in the metal can. They also work, but the black body ones seem to have slightly better reception from off-angles and hide in the project more easily.

**Comment by haizaar** [comment]
I hear you. Ordered the one you suggested. The scarcest resource in this project is time. I want to keep it low-budget, but not complete el-cheapo :)

Thanks!
