### ISSUE TITLE
How many channels Nano can drive?

### ISSUE THREAD

**Issue by haizaar** [haizaar/doll-house-lights#2]
I understand there are two options - connects LED serially, or connect them as several channels and drive them separately, even 8 channels with 1 led per each.

I'm thinking out loud here... 1 channel per led approach has a bonus that when installing - I need only one cable visible in the room (no exit cable).

While routing 8 channels requires more initial effort, I think it's easier to maintain/debug if something goes wrong - I can loose one channel/room and the rest will keep working.

The question is whether Auduino Nano can handle 8 channels (enough pins, etc.).

Again, if it's not something straight-forward (soldering/wiring aside), let's skip it for the first version.

**Comment by haizaar** [comment]
Looking at APA102 [tutorial](https://www.youtube.com/watch?v=QQWqhX8AdDs), seems like adruino only need to drive clock and data, i.e. 2x8 pins. So Nano should have enough.

Further question: can all led channels share single clock pin? This way I'll only need 1 clock + 8 data pins.

**Comment by jim-sokoloff** [comment]
Hah. I just commented on the other issue to that effect. The APA102 should work fine on a shared clock. I'll see if I can test and prove that this weekend, but in principle, it should work.

**Comment by jim-sokoloff** [comment]
The Nano has 14 digital pins; it should be possible to run therefore 13 individual LEDs [though we are likely to not want to use TxD/RxD, and perhaps not the SPI pins to make it easier to program and debug]. Still, even with that, you should be good to go for 8 channels.

**Comment by haizaar** [comment]
From what I read, analog pins can work as digital as well (but not vice
versa). Hence it gives us another 8, right?

(Not that I'll need those, but in case me out someone else wants to extend
it in the future)

**Comment by jim-sokoloff** [comment]
You're right. It appears to be 22 in total perhaps. (I first just googled "Arduino nano how many digital pins" and took the answer of 14 to be "enough for haizaar's use case".)

**Comment by haizaar** [comment]
Looks like this one is clear now. Closing :)
