### ISSUE TITLE
Can I use USB cables for wiring

### ISSUE THREAD

**Issue by haizaar** [haizaar/doll-house-lights#3]
Hi Jim (I hope that's the right name),

Can I use use USB cable (just the cable, not connectors) for wiring? They also have 4 pins and can handle 1a of current which should be enough for 8 leds strip, right? 

I ordered those 4 wire cables you suggested, just in case, but they are quite bulky to route, particularly with single channel approach where they need to go both in and out in each room - hence I'm thinking of something leaner, like USB, or may be plain old phone 2-pair cable.

I know USB wires are tiny, but I repaired them in the pas and I'm capable to solder them.

What do you think?

**Comment by jim-sokoloff** [comment]
Electrically, any 4 wires will work. For that short a run, 4 strands of rusted barbed wire would probably work... :)

I would bias towards the flat telephone cable over USB, but you need +5V, GND, clock, and data going to each and from each LED. You can share the +5V and GND in any topology you want, so an "out and back" run of wire only needs 6 wires, not 8 (5V, GND, clock in, data in, clock out, data out), so you could use ethernet patch cables as well.

The other thing is with so few LEDs in total, you could do a runs of "a single LED". Wire the 5V and GND to each LED, and then use 2 AVR pins to drive each single LED (or even 1 pin for a common clock and 1 pin for each LED). 

So, as you think about the wiring, it's possible for us to drive at least 10 [and maybe up to 13] LEDs as "strings of 1" if that helps your wiring planning. (I'll see if I can verify that 100% with the parts I have on hand sometime this weekend.

**Comment by haizaar** [comment]
OK. I think I'll go with USB cables path. I already got a bunch of micro-usb female sockets and soap-shell like project box on order. I can assemble those into a box together with arduino and have no soldered wires coming out from the controller box (except for the AR sensor may be). Then I can buy a bunch of cheap micro-usb charging cables, cut the USB-A end and solder it to leds - this way I can easily plug in/out led strip into/off a controller.

Thanks again for answering. My original question is clear for me, so I'm closing this one as well.

Cheers.
